### ISSUE TITLE
Include earthquake coordinates in the message body

### ISSUE THREAD

**Issue by nagellette** [Geomates/KandilliEarthquakeNotifier#1]
Telegram message body includes only "Yer" column from Kandilli page. To enable geospatial analysis or visualisation using common navigation applications, lat/lon information better be included in the message.

**Comment by mtrcn** [comment]
I added Google Maps link via using Telegram API's markdown style support. Addressed here; https://github.com/Geomates/KandilliEarthquakeNotifier/commit/aa0eff364c1cc86aa9d14ab98ba946a16995c7fd
