### ISSUE TITLE
Notification Filter

### ISSUE THREAD

**Issue by amaeksi** [Geomates/KandilliEarthquakeNotifier#6]
Kandilli's twitter account is filtering lesser magnitude earthquakes like 2.0. I assume that their threshold is 3.00. If you apply a filter like that it will be better for the user.

**Comment by mtrcn** [comment]
Hey, thank you for the suggestion 🙌. Good news, it has already this functionality via Bot; https://t.me/kandilli_bot Check this out and let me know if it is fine 🤞.
